In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [9]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [10]:
df.shape

(569, 33)

In [11]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [12]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train test split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [15]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [17]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [18]:
len(df.columns)

31

In [19]:
len(X_train) + len(X_test)

569

In [20]:
X_train

array([[ 1.35165783, -0.09417474,  1.26081104, ...,  0.06388628,
        -0.14183149, -1.03234562],
       [ 1.25349412, -0.40112971,  1.27300715, ...,  1.81616105,
         1.3582881 ,  0.40936627],
       [-0.36480469,  2.25133611, -0.40192584, ..., -0.79518152,
        -0.87623242, -0.65010658],
       ...,
       [-0.27225033,  2.04982369, -0.30517   , ..., -0.57388131,
        -0.71807785, -1.08578275],
       [-0.7714829 , -0.46908157, -0.76130467, ..., -0.80892782,
        -0.54426441, -0.18444018],
       [-0.36480469, -0.25585331, -0.3226511 , ..., -0.12040468,
        -0.54739618,  0.25014544]], shape=(455, 30))

In [21]:
y_train

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0])

In [23]:
X_train

array([[ 1.35165783, -0.09417474,  1.26081104, ...,  0.06388628,
        -0.14183149, -1.03234562],
       [ 1.25349412, -0.40112971,  1.27300715, ...,  1.81616105,
         1.3582881 ,  0.40936627],
       [-0.36480469,  2.25133611, -0.40192584, ..., -0.79518152,
        -0.87623242, -0.65010658],
       ...,
       [-0.27225033,  2.04982369, -0.30517   , ..., -0.57388131,
        -0.71807785, -1.08578275],
       [-0.7714829 , -0.46908157, -0.76130467, ..., -0.80892782,
        -0.54426441, -0.18444018],
       [-0.36480469, -0.25585331, -0.3226511 , ..., -0.12040468,
        -0.54739618,  0.25014544]], shape=(455, 30))

In [24]:
type(y_train)

numpy.ndarray

In [25]:
type(y_test)

numpy.ndarray

# Numpy Array to tensors

In [26]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

#by changing dtype. main correct way
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32) #corre
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)



y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

/var/folders/n9/zntydnf54wn0nll65r9v5kww0000gn/T/ipykernel_3620/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/var/folders/n9/zntydnf54wn0nll65r9v5kww0000gn/T/ipykernel_3620/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/var/folders/n9/zntydnf54wn0nll65r9v5kww0000gn/T/ipykernel_3620/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/var/folders/n9/zntydnf54wn0nll65r9v5kww0000gn/T/ipykernel_3620/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [27]:
type(X_train_tensor)

torch.Tensor

# Dataset and Dataloader

In [28]:
from torch.utils.data import Dataset,DataLoader

In [29]:
class CustomDataset(Dataset):
  def __init__( self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index], self.labels[index]

In [30]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [31]:
len(train_dataset)

455

In [32]:
train_dataset[2]

(tensor([-0.3648,  2.2513, -0.4019, -0.4090, -1.1305, -0.9013, -0.3610, -0.6845,
         -0.9090, -0.8372, -0.6803,  0.2615, -0.6618, -0.5012,  0.4259, -0.2341,
          0.2600, -0.7248, -0.4467, -0.4210, -0.5029,  1.6600, -0.5623, -0.5089,
         -0.4613, -0.6099, -0.1652, -0.7952, -0.8762, -0.6501]),
 tensor(0.))

# Loader

In [33]:
# data gula etar moddhe alada kore load kore rakhlam. train and test data..
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True) #ekhane shuflle false dewa uchit always for test loader

# Defining the Model

In [34]:
X_train.shape[1]

30

In [35]:
import torch.nn as nn

In [36]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [37]:
torch.rand(30,1)

tensor([[4.9176e-01],
        [8.9667e-02],
        [9.3829e-01],
        [8.8312e-01],
        [7.8745e-01],
        [2.5058e-01],
        [7.5024e-01],
        [6.5935e-01],
        [9.5959e-01],
        [1.1845e-01],
        [1.2910e-01],
        [1.7610e-01],
        [5.2404e-01],
        [5.5625e-01],
        [9.8966e-01],
        [7.4335e-01],
        [4.2774e-03],
        [5.9526e-01],
        [7.5016e-01],
        [8.1689e-01],
        [9.1593e-01],
        [1.2828e-01],
        [6.3982e-01],
        [3.1142e-01],
        [1.0935e-01],
        [5.2234e-02],
        [7.6534e-01],
        [5.1815e-01],
        [4.0698e-04],
        [2.6906e-01]])

# Parameters

In [38]:
X_train_tensor.shape[1]

30

In [39]:
learning_rate = 0.1
epochs = 25

In [40]:
loss_function = nn.BCELoss() #binary cross entropy loss function

In [41]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [42]:
model = MySimpleNN(X_train_tensor.shape[1])

In [43]:
model.parameters()

In [44]:
X_test_tensor.dtype

torch.float32

In [45]:
model.linear.weight.dtype

torch.float32

In [46]:
y_train_tensor.dtype

torch.float32

In [47]:
model.parameters()

# Training Pipeline Main

In [48]:
# ei kaaj gula dataset dataloader diye kora hoise..eta industry project ah kore eibhabei..amra etai use korbo..mini batch er issue gulau eta diye korle solve hobe.

#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):


    
  for batch_feature,batch_labels in train_loader:
    #forward pass
    y_pred = model(batch_feature)
    #Loss calculate
    loss = loss_function(y_pred,batch_labels.reshape(-1,1))

    #zero gradient
    optimizer.zero_grad()
    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.2659059464931488
 2 , Loss = 0.252298504114151
 3 , Loss = 0.20303544402122498
 4 , Loss = 0.08532261103391647
 5 , Loss = 0.06756418198347092
 6 , Loss = 0.027916064485907555
 7 , Loss = 0.05876745656132698
 8 , Loss = 0.10262824594974518
 9 , Loss = 0.33536794781684875
 10 , Loss = 0.07749130576848984
 11 , Loss = 0.003948271740227938
 12 , Loss = 0.08214451372623444
 13 , Loss = 0.02699248492717743
 14 , Loss = 0.17831231653690338
 15 , Loss = 0.06933653354644775
 16 , Loss = 0.03397266939282417
 17 , Loss = 0.14855508506298065
 18 , Loss = 0.014880050905048847
 19 , Loss = 0.0952613577246666
 20 , Loss = 0.012563838623464108
 21 , Loss = 0.011818794533610344
 22 , Loss = 0.035577502101659775
 23 , Loss = 0.113906629383564
 24 , Loss = 0.0683913305401802
 25 , Loss = 0.006011344492435455

# Training pipeline version 2

In [49]:
# eta mini batch gradient descent diye kora..eta mainly amra research er jonno beshi use kori..shikhe rakhlam..ekhane rakha hoise example hishabe jodi kokhono laage...


#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop
batch_size = 32
epoch = 25
n_sample = len(X_train_tensor)

for epoch in range(epochs):

  for start_indx in range(0,n_sample,batch_size):
    end_indx = start_indx + batch_size

    print(f" Start index {start_indx}, end indx {end_indx}\n")

    X_batch = X_train_tensor[start_indx:end_indx]
    y_batch = y_train_tensor[start_indx:end_indx]

    #forward pass
    y_pred = model(X_batch)
    loss = loss_function(y_pred,y_batch.reshape(-1,1))


    #upate step

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()



  #print loss in each epoch

  # print(f" {epoch+1} , Loss = {loss.item()} ")

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

# Model Evaluation (old)

In [50]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.569252073764801

# Better version of Model Evaluation

In [51]:
y_pred.shape

torch.Size([114, 1])

In [52]:
batch_labels.shape

torch.Size([7])

In [53]:
model.eval()  #evaluation mode # eta korle self.training tah false hoye jabe
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item() # ekhane shape thik rakha tah important..pyTorch ah shape thik nah thakle pore issue hoy

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)

0.984375

In [54]:
accuracy_list

[0.9375, 1.0, 1.0, 1.0]

# Summary

In [55]:
X_train_tensor.shape

torch.Size([455, 30])

In [56]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /opt/anaconda3/lib/python3.13/site-packages (1.8.0)

In [57]:
from torchinfo import summary

In [58]:
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================