In [58]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [59]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [60]:
df.shape

(569, 33)

In [61]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [62]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [63]:
df.shape

(569, 31)

## train test split

In [64]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [65]:
df["diagnosis"].nunique()

2

In [66]:
df["diagnosis"].unique()

array(['M', 'B'], dtype=object)

## scaling

In [67]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [68]:
X_train

array([[-1.45801784, -0.11260054, -1.33054232, ...,  0.01095176,
         0.38499284,  1.17276053],
       [-0.33991103, -0.77856802, -0.36817744, ..., -0.12518505,
         0.77482204,  0.6485128 ],
       [-0.777655  ,  0.22963274, -0.6001128 , ...,  2.19831844,
         5.95875489,  4.83598224],
       ...,
       [-1.57932728, -1.75670774, -1.56956923, ..., -1.06452902,
         0.52023971,  0.34568647],
       [-0.31130032, -0.18428454, -0.28683321, ...,  0.18379962,
         0.34998777, -0.03908749],
       [-1.83367655,  1.41126253, -1.83487658, ..., -1.74047121,
         0.26247509,  0.84062843]], shape=(455, 30))

In [42]:
y_train

355    B
456    B
421    B
470    B
482    B
      ..
514    M
437    B
223    M
118    M
42     M
Name: diagnosis, Length: 455, dtype: object

## Label Encoding

In [69]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [71]:
y_train

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0])

In [72]:
type(X_train)

numpy.ndarray

In [73]:
type(y_test)

numpy.ndarray

## Numpy arrays to PyTorch tensors

In [74]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [75]:
type(X_train_tensor)

torch.Tensor

In [78]:
X_train_tensor.shape

torch.Size([455, 30])

In [79]:
y_train_tensor.shape

torch.Size([455])

## Defining the model

In [80]:
class MySimpleNN(): 
    def __init__(self,X): 
        #initialize
        self.weights= torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True) 
        
    def forward(self,X): 
        #forward function
        z=torch.matmul(X,self.weights)+self.bias #x and weight matrix multiplication. w*x+b
        y_pred=torch.sigmoid(z) 
        return y_pred 

    def loss_function(self,y_pred,y):
        #loss function
        # Clamp predictions to avoid log(0)
        epsilon=1e-7
        y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

        # Calculate loss

        loss= -(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss

## Important Parameters

In [81]:
learning_rate=0.1
epochs=25

## Training Pipeline

In [82]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.512579161993106
Epoch: 2, Loss: 3.3698606467135543
Epoch: 3, Loss: 3.2163181790051723
Epoch: 4, Loss: 3.063396277243017
Epoch: 5, Loss: 2.9001835593072673
Epoch: 6, Loss: 2.73570056015102
Epoch: 7, Loss: 2.569562300411912
Epoch: 8, Loss: 2.3997792631594
Epoch: 9, Loss: 2.2299208177016063
Epoch: 10, Loss: 2.056475623207341
Epoch: 11, Loss: 1.884415407625174
Epoch: 12, Loss: 1.7174609148839768
Epoch: 13, Loss: 1.5560309581787284
Epoch: 14, Loss: 1.4067990837980093
Epoch: 15, Loss: 1.2718065354398118
Epoch: 16, Loss: 1.1529717106046138
Epoch: 17, Loss: 1.0518019836374402
Epoch: 18, Loss: 0.9690018121377363
Epoch: 19, Loss: 0.9040747211523232
Epoch: 20, Loss: 0.8551970207783749
Epoch: 21, Loss: 0.8195650262511851
Epoch: 22, Loss: 0.7940494185511543
Epoch: 23, Loss: 0.7757960399319028
Epoch: 24, Loss: 0.762545983901186
Epoch: 25, Loss: 0.7526779043169882

In [83]:
model.bias

tensor([-0.1378], dtype=torch.float64, requires_grad=True)

## Model Evaluation

In [84]:
with torch.no_grad():
    y_pred=model.forward(X_train_tensor)
    y_pred=(y_pred>0.9).float()
    accuracy=(y_pred==y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.672353982925415